services:
  - type: web
    name: fir-legal-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_deploy.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: PORT
        value: 10000 